### ISSUE TITLE
Sorting issue on `tokens/v4`

### ISSUE THREAD

**Issue by diegoramosxyz** [reservoirprotocol/indexer#1003]
The following calls should return the same results, but when `contract` is used, the sorting doesn't work. 

https://api-rinkeby.reservoir.tools/tokens/v4?collection=0x4d68e14cd7dec510c84326f54ee41f88e8fad59b&sortBy=floorAskPrice

This call is not sorting by `floorAskPrice`:

https://api-rinkeby.reservoir.tools/tokens/v4?contract=0x4d68e14cd7dec510c84326f54ee41f88e8fad59b&sortBy=floorAskPrice

**Comment by georgeroman** [comment]
@diegoramosxyz This is by design, when filtering by contract the sorting is going to be by token id. We should probably document that and also fail the API if conflicting options are used.
