### ISSUE TITLE
Backfill `fillSource`

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1103]
- Properly attribute all Reservoir, Gem and Genie fills to the beginning of time
- Also capture the `referrer` for Reservoir fills

**Comment by ptrwtts** [comment]
I also noticed that there seems to be a very low number for `reservoir` as the fill source. Around 25 a day, despite over 100 daily txs on the router. Seems the issue is seaport related. I see reservoir fills for all exchanges except seaport.

**Comment by georgeroman** [comment]
The fill source is currently backfilling, I'll be monitoring over the weekend, but it will probably take a while to finish.
