### ISSUE TITLE
Goerli

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1105]

**Comment by ptrwtts** [comment]
Perhaps we can get this up and running without a metadata provider initially. So effectively liquidity only. And then just do custom metadata for the tokens we need to test with.

**Comment by ptrwtts** [comment]
Related, we may want to implement this task, so that all tokens have basic metadata, even when no metadata provider is available: https://github.com/reservoirprotocol/indexer/issues/1132

**Comment by georgeroman** [comment]
Goerli indexer is up: https://api-goerli.reservoir.tools/, currently syncing.
