### ISSUE TITLE
Animation URL

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1133]
In addition to an `image`, many tokens have an `animation_url`, which can be a video, html, gif, etc. We just need to start saving this when available from a metadata provider, and returning it Token Details API.

**Comment by georgeroman** [comment]
We actually already support this when fetching metadata via OpenSea: https://github.com/reservoirprotocol/metadata/blob/191306ba3402058bf6c13cb09abace767d2ccc9f/src/parsers/opensea.js#L10. The `media_url` field is saved in the `media` column of the `tokens` table: https://github.com/reservoirprotocol/indexer/blob/d462a7c0311c132317937f53b1823b2d81a28cd2/src/jobs/metadata-index/write-queue.ts#L49.

**Comment by ptrwtts** [comment]
Awesome so it just needs to be added in the response?

**Comment by georgeroman** [comment]
Yes, that should be it

**Comment by ptrwtts** [comment]
OK, cool, then let's just return an extra `media` field in both tokens and tokens/details
