### ISSUE TITLE
Improve collection search

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#114]
Long term, we probably want to run a separate service like [Typesense](https://typesense.org/) for search. 

But in the short term, we should at least make collection searching more efficient. Postgres has something called `ts_query` that seems to do the job. We just need an extra column that breaks the collection name up into pieces for more efficient searching. There's various tutorials around, like this: https://dev.to/akshaynathan/keep-it-simple-stupid-building-full-text-search-across-all-your-tools-with-postgres-27ho

Might also be worth trying the same thing on token names.

**Comment by georgeroman** [comment]
The [`pg_trgm`](https://www.postgresql.org/docs/9.6/pgtrgm.html) Postgres extension seems to be working pretty good for the ~40k collections that we have on mainnet.

**Comment by ptrwtts** [comment]
Reviving this old thread because collection name searching is actually pretty slow (1-5s), which makes it not really usable for autocomplete like we want. 

Does `pg_trgm` have support for indexing on a second column? I assume the issue is that it's slow because we need to sort by volume after we've done the filtering. Ideally, it could be done purely on the index.

**Comment by georgeroman** [comment]
> Reviving this old thread because collection name searching is actually pretty slow (1-5s), which makes it not really usable for autocomplete like we want.
> 
> Does `pg_trgm` have support for indexing on a second column? I assume the issue is that it's slow because we need to sort by volume after we've done the filtering. Ideally, it could be done purely on the index.

Not really, there is a `btree_gin` Postgres extension to allow multiple columns in a GIN index (the type of index `pg_trgm` uses) but it would be redundant in our case since GIN indexes cannot help with ordering.

**Comment by ipeleg** [comment]
I created a new API dedicated for search as it can be much more lightweight in terms of data we return thus much faster
