### ISSUE TITLE
Update transactions table to include extra data

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1148]
- block number
- block timestamp (not critical, but saves needing to always join on blocks)
- tx fee
- gas usage

Backfill existing records too

**Comment by georgeroman** [comment]
For the moment this is missing the gas fields (eg. `gas_price`, `gas_used`, `tx_fee` (`gas_price` * `gas_used`)) due to the need to make an additional RPC call to get them.
