### ISSUE TITLE
Improved metadata rate-limit handling

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1255]
Currently, if the metadata service is rate-limited, so the indexer just keeps retrying, which can cause it to get stuck, because it does back off. The metadata service will return an error with 429 in it when it is rate-limited, and we should use this to implement a basic exponential backoff.

**Comment by nofir** [comment]
Opensea returns the following "Request was throttled. Expected available in 1 second.", we can maybe utilize it to make the backoff more accurate.
