### ISSUE TITLE
BUG: Incorrectly classified looksrare sales

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1315]
```select * from public.fill_events_2 where tx_hash = '\x178228b7b543da65ee9d76ae187789a918c106f8344b0579deb8b1fa407c3c09'```

This is classified as a `buy`, even though it is sell orders being filled: https://etherscan.io/tx/0x178228B7B543DA65EE9D76AE187789A918C106F8344B0579DEB8B1FA407C3C09 

It seems to happen with old LooksRare transactions (before May 26) filled via Gem/Genie.

**Comment by georgeroman** [comment]
Backfill running, should be done over the weekend.
