### ISSUE TITLE
Sort tokens by "recently created"

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1422]
Apparently if you used the sort of by topBidValue, and there were no bids, it would show newest tokens first, which is nice in some cases. Probably a result of the underlying index. But when we removed that sort option, we lost it. Perhaps we can bring it back more explicitly with a dedicated sort option. Could maybe just allow changing the sort direction, then could use the token id sort.

**Comment by ptrwtts** [comment]
Don't want to spend time on this or add new indexes. Just a quick check if we can easily revive this capability

**Comment by ipeleg** [comment]
If there were no bids it was sorting by the token_id, which I guess in most cases token Id 0 was the first to be minuted and token 10000 was the last to be minted within the collection, in the tokens/v4 we already have that sortBy called tokenId, we could add the same on tokenDetails/v4, let me know if that sounds good

**Comment by ptrwtts** [comment]
The main thing is the ability to sort by token id DESC. Apparently that's
what it was doing

**Comment by ipeleg** [comment]
no problem, i'll add the DESC option on tokens/tokens-details
