### ISSUE TITLE
ERC-20 Liquidity

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1472]

**Comment by ptrwtts** [comment]
Standard `price` object to use:

- currency
  - address
  - name
  - logo
  - decimals
- amount
  - raw (string)
  - decimal (converted to 6 decimals)
  - usd (converted to 6 decimals)
  - native (converted to 6 decimals)

**Comment by ptrwtts** [comment]
Standard `price` object to use:

- currency
  - address
  - name
  - logo
  - decimals
- amount
  - raw (string)
  - decimal (converted to 6 decimals)
  - usd (converted to 6 decimals)
  - native (converted to 6 decimals)

**Comment by georgeroman** [comment]
Do we want to return this object for ETH/WETH prices as well?
