### ISSUE TITLE
Set multiple fees in List API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1540]

**Comment by georgeroman** [comment]
As discussed, this is already available.

**Comment by elie222** [comment]
> As discussed, this is already available.

Where was this discussed? Seems like joi is expecting it to be a string and not an array.

```ts
          feeRecipient: Joi.string()
            .lowercase()
            .pattern(regex.address)
            .description(
              "Wallet address of fee recipient. Example: `0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00`"
            )
            .disallow(AddressZero),
```

**Comment by georgeroman** [comment]
> > As discussed, this is already available.
> 
> Where was this discussed? Seems like listing supports it but bids don't at this time. Is that accurate?
> 
> ```ts
>           feeRecipient: Joi.string()
>             .lowercase()
>             .pattern(regex.address)
>             .description(
>               "Wallet address of fee recipient. Example: `0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00`"
>             )
>             .disallow(AddressZero),
> ```

Right, created a new issue for that, I'll try to add it in the following days: https://github.com/reservoirprotocol/indexer/issues/1596
