### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Sparkluis5** [reservoirprotocol/indexer#1590]
Hey guys first of all amazing work

I was trying to run the indexer locally and some situations lack documentation on how to execute them. For example i have tried to add several URLs to obtain token metadata but without success. I also tried to disable some jobs without the admin panel but with no success.
I know that documentation is probably the most tedious and a low priority issue but it would help newcomers contribute to the project.

Thanks and keep up the good work 😊

**Comment by ptrwtts** [comment]
Thanks @Sparkluis5 

Any reason you need to run it yourself vs using the hosted version? Unfortunately it's probably not something we will have time to invest in for at least a couple more months. You can see more detail here:

https://docs.reservoir.tools/docs/hosted-vs-self-hosted

That said, feel free to DM us and explain your use-case, and we'll see the best option to support it.

**Comment by Sparkluis5** [comment]
Hi, thanks for the reply @Sparkluis5 

The main reason we are trying to run it ourselves is mainly to obtain the full historical data (more than 3 months data) regarding to a user/wallet address and also to add the buy price value when a user bought a specific token (currently only supports the timestamp when the user acquired the token). 

Maybe these are some use cases that you haven't considered, but i understand that you have a lot on your plate. Wish you the best for the future developments

**Comment by ptrwtts** [comment]
Is this for offline data analysis, or want the custom data to be querable via API?

- For bulk data hopefully we can be doing dumps soon to make this easier
- Showing the acquisition price is definitely on the roadmap. We just started recording mint prices, which was a prerequisite to having good data

**Comment by Sparkluis5** [comment]
At the moment a queryable API. I understand that the response time with such large amount of data is very hard to achieve and reservoir manages to do that really well.
