### ISSUE TITLE
Set multiple fees in Bid API

### ISSUE THREAD

**Issue by georgeroman** [reservoirprotocol/indexer#1596]

**Comment by georgeroman** [comment]
@elie222 Added new versions v4 for both the /execute/list/v4 and /execute/bid/v4 which now support an array of fees:
- https://github.com/reservoirprotocol/indexer/blob/d7497c0bc8b8d305c8b0112707fad0063226126a/src/api/endpoints/execute/get-execute-list/v4.ts#L90-L94
- https://github.com/reservoirprotocol/indexer/blob/300963c4370d4f2f1af91a59f8bdc28ffbc38fb6/src/api/endpoints/execute/get-execute-bid/v4.ts#L101-L105

The client SDK will integrate these probably early next week.

**Comment by elie222** [comment]
Was this changed again?

I'm seeing this in reservoir kit:

```
    marketplaceFee?: number;
    marketplaceFeeRecipient?: string;
```

**Comment by georgeroman** [comment]
Not changed from the perspective of the indexer / apis. Reservoir kit might have its own abstractions on top.
