### ISSUE TITLE
Additional actions when refreshing collections/tokens

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#314]
When we refresh a token or collection, we want to do more, to increase the odds that it fixes the issue that the user is having. Here's a full list of what we want. Some we have already, some we need to add. 

For the ones we need to add, admin APIs already exist for them, we just need to trigger from the public APIs.

**Collection**

- refresh collection metadata
- refresh all tokens metadata
- refetch orders (we should extend this to look further to reach more tokens)
- _revalidate existing orders_
- _recalculate cache_

**Token**

- refresh token metadata
- refetch orders
- _revalidate existing orders_
- _recalculate cache_
- _on-chain re-validation of the floor ask order_

**Comment by ptrwtts** [comment]
@ipeleg We added order refreshing, but just realized we missed cache refreshing (ie update tokens table to have the current floor ask for every token). These are the admin equivalents that we want to do in public refresh:

Token > https://api.reservoir.tools/#/x-admin/postAdminFixtokencache
Collection > https://api.reservoir.tools/#/x-admin/postAdminFixcache

**Comment by ipeleg** [comment]
Added the above refresh updates to the public APIs as well
