### ISSUE TITLE
Order Events API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#329]
Any time the status of an order changes, we check if it impacted the "floor ask" of the token (aka best price), and if so, generate an [event](https://api.reservoir.tools/#/2.%20Aggregator/getEventsTokensFlooraskV1). This is great for developers who only need token level granularity. They don't care about all of the underlying orders. They don't need to know about depth, just the single best price. 

But for other use cases, depth is required. For example, it matters more with 1155 tokens. Or an advanced price model that wants all available signal to be as accurate as possible. So the idea is to create a similar API, but with order-level granularity. Trigger an event any time the status of any order changes. What's nice about this is that it's also the most granular unit of information. You could use order events to derive token floor events, or to keep your own DB fully in sync. So seems like a valuable thing to offer.

**Comment by ptrwtts** [comment]
Asks only, with the following fields:

Order
- orderId
- status (active, inactive, filled, cancelled, expired)
- price
- maker
- contract
- tokenId
- source
- validFrom
- validUntil

Event
- id
- kind
- txHash, 
- txTimestamp, 
- createdAt

**Comment by georgeroman** [comment]
https://api.reservoir.tools/events/orders/v1
