### ISSUE TITLE
Orders/all should allow querying all with no filter

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#332]

**Comment by ptrwtts** [comment]
Let's discuss this, due to the large number of indexes on this table, which maybe we can consolidate. 

One of the reasons people want this ability is in order to show a real-time feed of new listings, as soon as they are created. We should also discuss how we can reduce the latency on this as much as possible, perhaps by storing the raw orders before validation.

**Comment by ptrwtts** [comment]
Summary of where we landed on the call:

- Separated by side
- Flag to include metadata
- Flag to include raw data
- New source format (for both query param and response)

**Comment by georgeroman** [comment]
@ptrwtts Just to confirm, we still want to be able to get all orders without passing `contract` or `source`, right?

**Comment by ptrwtts** [comment]
Yes thanks

**Comment by georgeroman** [comment]
https://api.reservoir.tools/orders/all/v1
