### ISSUE TITLE
Collection Floor Events API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#337]
Similar to the token floor API that we have, but for the whole collection, generates an event when the floor price changes, so you can quickly look back historically at collection floor.

We should be able to bootstrap this from the token floor price events.

**Comment by ptrwtts** [comment]
Thinking about this more, I think we should just try an get it up and running ASAP, in the quickest way possible. We can always go back and do the bootstrapping off token floor events if we decide it's worthwhile.

So process would be:

- Start caching collection floor
- Bootstrap events table with current floor of all collections
- Log an event any time the collection flor changes

**Comment by georgeroman** [comment]
https://api.reservoir.tools/events/collections/floor-ask/v1
https://api.reservoir.tools/events/collections/floor-ask/v1?collection=0x519272821dddb3afc7accd1823b674d30946185e

**Comment by ptrwtts** [comment]
Excellent.

One thing is that it would be good to get the contract + token id returned within the `floorAsk` node.
