### ISSUE TITLE
Optimized bootstrapping for floor ask events

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#371]
**Background**

When someone wants to start leveraging the floor ask events API to subscribe to token price changes, they need to bootstrap their DB with the current prices. They have two options, neither of which is ideal:

1) Iterate through all events from the beginning of time > a lot of wasted queries
2) Use the tokens/floor to get all prices > missing additional info they may need, like source, maker, expiry, etc

Both are these are problematic when trying to subscribe to a single collection, and unworkable if trying to subscribe to everything. We need a solution that is optimal, that we can recommend.

**Proposal**

Add a query parameter, of bootstrap=true, which means the API will only return the most recent event per token, and only if the price is non zero. This returns the minimum number of records to get the price for every currently listed token.

Ideally, this would work in conjunction with `endTimestamp` which would unlock two powerful features:

1) You could specify an `endTimestamp` for bootstrapping, and then once it's done, start realtime polling from `t + 1` for a clean transition from bootstrap to realtime

2) It would make it possible to get the liquidity at any point in time in the past

**Implementation**

Naively, I thought that maybe we could leverage `DISTINCT ON` with existing indexes, but it didn't seem to work. If we can pull it off with the addition of only one index, it's probably worth it. 

However, if it's too inefficient to get this from the floor ask events table, we could always just get it from the tokens table. It would effectively be the `tokens/floor` API, but returning extra info per token. The downside of doing it this way is that you wouldn't be able to pass an `endTimestamp`, for a snapshot in time, but we can live without this if it's too hard.

The fields we need returned are the same as the floor ask events API, but no need for the event information. So:

```
        "contract": "string",
        "tokenId": "string"
        "orderId": "string",
        "maker": "string",
        "price": 0,
        "validUntil": 0,
        "source": "string"
```

**Comment by georgeroman** [comment]
I got the bootstrap API working off the cached token floors for now: https://api.reservoir.tools/tokens/bootstrap/v1?contract=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d

**Comment by ptrwtts** [comment]
Good move. Better to have that than nothing. A couple of questions:

1) Wouldn't it be faster if sorted by floor price, given that we need to filter out null price tokens?

2) Should it return all tokens at once? Similar to the floor API, you're always wanting the whole collection. There's no scenario where you only get a few. So wouldn't it be better for the user, and in terms of DB load, if it was done in one batch? I assume the main concern is large collections. Maybe a middle-ground would be to give it a large limit, of say 5000, that would only apply to really large contracts/collections, so you can ignore it most cases. Pagination could miss tokens if we sort by price, but I don't think it's a big deal. We should be optimizing for small collections.

**Comment by ptrwtts** [comment]
Also got a request to add `validFrom` and `tokenImage` to this API, which I think we should do, whilst continuing to evaluate the plan for this API long term. I assume we access to the data for both of these without any joins (already joining on orders I believe)

**Comment by georgeroman** [comment]
> Good move. Better to have that than nothing. A couple of questions:
> 
>     1. Wouldn't it be faster if sorted by floor price, given that we need to filter out null price tokens?
> 
>     2. Should it return all tokens at once? Similar to the floor API, you're always wanting the whole collection. There's no scenario where you only get a few. So wouldn't it be better for the user, and in terms of DB load, if it was done in one batch? I assume the main concern is large collections. Maybe a middle-ground would be to give it a large limit, of say 5000, that would only apply to really large contracts/collections, so you can ignore it most cases. Pagination could miss tokens if we sort by price, but I don't think it's a big deal. We should be optimizing for small collections.

1. Yes, I'm going to add that back.
2. Just did some tests and looks like 1000 worked as a default limit, any limit greater than that seems to timeout (although even 1000 seems to be at the edge of timeout).

**Comment by ptrwtts** [comment]
Hmm do you think it's the join on orders that makes it slow, or the amount
of data returned?

**Comment by ptrwtts** [comment]
Perhaps we just need to do pagination. But at that point, it basically
becomes the tokens API....

**Comment by ptrwtts** [comment]
- Max 500
- Add `validUntil`

**Comment by georgeroman** [comment]
https://api.reservoir.tools/tokens/bootstrap/v1?collection=0x7ab2352b1d2e185560494d5e577f9d3c238b78c5
