### ISSUE TITLE
BUG: User collections times out

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#487]
https://api.reservoir.tools/users/0xD5c0D17cCb9071D27a4F7eD8255F59989b9aee0d/collections/v1
https://api.reservoir.tools/users/0x37b2ee54A9C20eca0010DafCF6Eb2d5cA45B5ACe/collections/v1

Did we possibly remove an index that was being relied on?

**Comment by ipeleg** [comment]
That's a strange one, for both of this owners the explain looks good, i'll take a deeper look there to see what's going on

**Comment by ipeleg** [comment]
Update the Join in the query there, looks much better for now
