### ISSUE TITLE
Handle unfillable orders due to custom contract logic

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#500]
Sometimes orders are unfillable due to custom logic like staking that is built into the contract. We need a way to gracefully handle these. It will likely require a new type of un-fillable status, in addition to no balance or no approval. For now, the only time this status would be toggled would be if performing an on-chain check via Admin API (#499). This will at least allow us to clear these. In the future, we may have more advanced logic to detect this sort of status change.

**Comment by georgeroman** [comment]
Maybe it's better to decouple the admin on-chain check from invalidating the order that failed on-chain validation. We might want to first take a look once we detect something that's not fillable to make sure it's not something on our side that caused it. For that we already have an API to invalidate an order (eg. mark it as cancelled (fillability status) and disabled (approval status)).
