### ISSUE TITLE
Return attribute stats in tokens/details

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#534]
Now that we have cached attribute stats, we can return it with each attribute in the tokens/details API. This is very useful for highlighting the most valuable attributes per token. We should return the following data per attribute:

- key
- value
- tokenCount
- onSaleCount
- floorAskPrice
- topBidValue

**Comment by ptrwtts** [comment]
Note that I think we currently get the attributes from a column directly in the tokens table. This was an experiment to improve performance, but not sure it really made a difference. What do you think @georgeroman? Agree that we can just get attributes from the normalized tables?

**Comment by georgeroman** [comment]
> Note that I think we currently get the attributes from a column directly in the tokens table. This was an experiment to improve performance, but not sure it really made a difference. What do you think @georgeroman? Agree that we can just get attributes from the normalized tables?

Actually the cached attributes in the tokens table are not used anymore, since it didn't actually give us any speed improvements.
