### ISSUE TITLE
Backfill source and validFrom in token floor ask events

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#702]
Cache everything that we currently join to get:

- source
- validFrom
- nonce
- anything else?

Then run a backfill and remove join

**Comment by georgeroman** [comment]
The backfilling is running, it's going to be a slow process though (any backfill on a huge table will be slow mostly because of the need to keep existing indexes up-to-date).

**Comment by ptrwtts** [comment]
Define "slow" hehe. Week? Month?

**Comment by georgeroman** [comment]
I would say probably around a week.
