### ISSUE TITLE
Slow LooksRare order ingestion

### ISSUE THREAD

**Issue by georgeroman** [reservoirprotocol/indexer#709]
LooksRare order ingestion seems to be extremely slow: https://app.datadoghq.com/logs?from_ts=1653117681686&index=&live=true&query=%22looks-rare%22+%22success%22&to_ts=1653121281686. It can pass up to 20 minutes without us receiving any orders. We should maybe recheck the ingestion mechanism and make sure we're not missing anything.

**Comment by ipeleg** [comment]
I've updated the logic there which caused triggering redundant backfilling processes, but the LooksRare sync will probably need to be revisited in order to fine tune it, for now it's working again and fetching every few seconds the latest new transactions
