### ISSUE TITLE
Non-aggregated order support

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#809]
It would be nice for us to support any valid order, even if we don't incorporate them into our aggregations (floor ask, etc):

 - private listings
 - listings in other ERC20 currencies (requires approval or conversion)
 - bundles
 - swaps

The most basic level of support would be:

- store and validate these orders
- allow fetching an order by ID
- allow fetching all orders per maker
- allow fetching all orders per private recipient
- support filling (the buy API probably needs the ability to fill by order id)
- support creation

For now, the main focus is creating and understanding Seaport orders. If it's not much additional effort, it would be good to understand historical Wyvern orders, but not critical and could be separate task if need be.

**Comment by ptrwtts** [comment]
After discussion, seems to be two major categories:

**Bundles**

- Create an arbitrary order with any set of offers, for any set of considerations
- If the bundle is fillable by a single taker, shows up in the takers bundle feed
- If all items offered are in a single collection, shows up in collection's feed
- Otherwise, the only way to discover it will be via the order ID

**Swaps**

- Allow offering any number of your items (including WETH), for a single item or token set
- In reverse, can discover all swaps that match any of your tokens
- It's always one token that you accept with, but may receive multiple

**Comment by ptrwtts** [comment]
Perhaps we keep track of the full offers and considerations array in the orders table, for looksup by ID, maker or private recipient, but then if the consideration is a single item (ETH, ERC20 or NFT), then we also store extra information. If it's ETH or ERC20, then it's effectively an "Ask". If it's an NFT then it's a "Swap".

**Comment by ptrwtts** [comment]
Once you get into swaps and bundles, you effectively are no longer in the territory of asks and bids:

  | Offer | Consideration
-- | -- | --
**Ask** | NFT | Currency
**Bid** | Currency | NFT
**Bundle Ask** | Bundle | Currency
**Bundle Bid** | Currency | Bundle
**Swap** | Bundle | NFT
**Bundle Swap** | Bundle | Bundle

A few notes: 

- "NFT" refers to a single NFT being traded, but it may be specified as a token set
- If the consideration is a single NFT, it's a special case, because can efficiently find the users who are eligible to fill
- If the ask is a currency, it's a special case, because anyone can fill (presuming they have the currency or can convert)

**Comment by georgeroman** [comment]
Basic bundle support is live on production (eg. opensea-style `bundle-ask` orders).
