### ISSUE TITLE
Flagged tokens

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#962]
- For each token, keep track of whether it's been flagged or not
- When fetching metadata from OpenSea, check the flagged status, and set on indexer
- Return `isFlagged` in the tokens and tokens/details APIs
- Return `flaggedCount` in the stats API

**Comment by georgeroman** [comment]
As part of this, we should also update any todos from creating bids that skip these flagged tokens (eg. https://github.com/reservoirprotocol/indexer/blob/96cba26df63f5138e28d33d00faaa11e85393948/src/orderbook/orders/seaport/build/buy/attribute.ts#L60).

**Comment by ptrwtts** [comment]
The main reason we need this is in order to build collection / trait bids that can be published to Open Sea's API. Given that they don't yet support it, bumping this down until they do.

**Comment by ptrwtts** [comment]
Let's try this again, with the following variation:

- Separate queue for checking single assets for flagged status
- API to let clients report a token as flagged, putting it into the queue for recheck
- When a collection offer is discovered with a merkle root that doesn't match ours, put whole collection into queue (top collections only)
- Keep track of when flag status was last checked, and return this in APIs, so that applications can decide whether or not to trust it
