### ISSUE TITLE
Improved source data in Sales APIs

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#970]
- Ensure orderSource is not null for bids
- If fill source is null, attribute the fill source to the order source
- Also return the `orderKind`

In a nutshell, the sources should almost never be null.

**Comment by ptrwtts** [comment]
@nofir i think something went wrong here. it seems that in the fills table, order source is only ever open sea, looks rare or x2y2. all the reservoir ones got overwritten. if you join on the orders table, it has the correct values.

**Comment by nofir** [comment]
Fixed issue and deployed a fix.
